name: KeloPaper
main: com.koisv.kelopaper.KeloPaper
version: 0.1-SNAPSHOT
api-version: 1.18
author: StayCake
libraries:
  - io.github.monun:kommand-core:2.10.0
  - org.jetbrains.kotlin:kotlin-stdlib:1.6.21
  - com.github.stefvanschie.inventoryframework:IF:0.10.5