name: KeloPaper
main: com.koisv.kelopaper.KeloPaper
version: 0.2-SNAPSHOT
api-version: 1.18
author: StayCake
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.6.21
  - com.github.stefvanschie.inventoryframework:IF:0.10.5